### PR TITLE
Forgotten Pleth file

### PR DESCRIPTION
**Pull request by W0584468**

### CODE REVIEW

**Comment by wrightaprilm** [comment]
Hey Denz,

I think you forgot to add and commit your notebook. If you're in your classroom_set directory, it should be in your projects.

**Comment by W0584468** [comment]
I am having trouble trying to put it in the class room set like pushing the
project to you

**Comment by wrightaprilm** [comment]
No prob, we can figure it out Tues.

**Comment by W0584468** [comment]
I have been trying. I am in the terminal and it doesn't give me an error I
thought I actually did it at one point.

**Comment by wrightaprilm** [comment]
OK, give it one more shot by adding, committing, and pushing. If it doesn't work, don't worry, and we'll handle it Tuesday.

**Comment by wrightaprilm** [comment]
Thank you!

**Pull request closed without merging**
